### ISSUE TITLE
Possible infinite loop while performing an outer join

### ISSUE THREAD

**Issue by carlamj** [guillemborrell/gtable#1]
`t1 = gtable.Table({'DATE': [numpy.datetime64('2017-04-30'), numpy.datetime64('2017-04-30'), 'VALUE': [10000000.0, 0.0])`
`t2 = gtable.Table({'DATE': [numpy.datetime64('2017-05-30'), numpy.datetime64('2017-06-30').required_columns('VALUE')
`
The following line keeps going forever:
`t3 = gtable.full_outer_join(t1, t2, 'DATE')`

I've ventured inside gtable code and I can tell the problem occurs when **full_outer_join** calls for **union_sorted** in joins.py, line 102 . Please check it out. Thanks!

**Comment by guillemborrell** [comment]
Fixed by 49a62eb0d1a5eeb8d8bf339b8280543b62ada7d9

Gracias Carla.
