### ISSUE TITLE
Adding a column full of strings

### ISSUE THREAD

**Issue by carlamj** [guillemborrell/gtable#2]
There is an issue while trying to fill a new column with strings: 

> File "***/valuation.py", line 407, in _compute_cash_flows
> cashflows_table.fill_column('POOL_ID', security)
> File "***/python3.6/site-packages/gtable/table.py", line 218, in fill_column
> col.fill(fillvalue)
> File "***/python3.6/site-packages/gtable/column.py", line 123, in fill
> new_values[~self.index.astype(np.bool_)] = fillvalue
> ValueError: could not convert string to float: '381AAA'

I can't really see where this type conversion is happening. I'm guessing in **column.fill**, at this line:
`new_values = np.empty(len(self.index), dtype=self.values.dtype)` the dtype is already established
 and maybe defaulted to float. But, at the method **table.required columns** (where this 'POOL_ID' column originated) there is no way to specify what type you want the columns to be. I tried to change it after creation but it didn't work.

Thanks!

**Comment by guillemborrell** [comment]
Can you please post a code snippet so I can test it faster?

**Comment by carlamj** [comment]
Here you go:
`
> import gtable as gt
> d = {'A': [1, 2, 3, 4], 'B': [2.2, 1.5, 7.3, 2.6]}
> t = gt.Table(d)
> t.required_columns('C')
> t.fill_column('C', 'hello')
`

**Comment by guillemborrell** [comment]
Hmm. This is complicated, because strings are a special case in Numpy, and there's no type promotion for them.
