### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by carlamj** [guillemborrell/gtable#5]
I would like for gtable to accept a previously computed boolean array as filter for a table. Currently, to achieve this one must have to explicitly instantiate a gtable.Column object with the boolean array and a full ones index for the filter_table function to swallow it up. Example:

```
#  whatever_filter -> boolean array, already computed
filtered_table = table.filter(gt.Column(whatever_filter, np.ones_like(whatever_filter)))
```

I'm aware this is mostly syntactic sugar. I'm willing to implement it myself, but I would like to hear your opinion first. Do I apply a decorator to filter_table? Put in an explicit type check? How would you do it? Would it kill performance?

**Comment by guillemborrell** [comment]
Let me see if there's something already implemented that can be reused

**Comment by guillemborrell** [comment]
I just implemented your version as the `gtable.Table.sieve` method. Feel free to improve that if you want, but the performance should be good. See 8d4df2a4e3b982df2832799e27ed92a0d9623d3f. You can also update to gtable-0.7.3 with this new function.

Is it ok to close?

**Comment by carlamj** [comment]
Sure! Thanks!
