### ISSUE TITLE
Filtering (again)

### ISSUE THREAD

**Issue by carlamj** [guillemborrell/gtable#6]
Hi Guillem, sorry to pester you again.

I'm afraid this time it might be a true bug though.  I'll post an example: 

```
ta = gt.Table({'A': [1, 2, 3, 1, 2, 3, 6], 'B': [0.2, 0.4, 0.4548, 0.34465, 0.4, 0.315456, 0.5454545]})
tb = gt.Table({'A': [1, 2, 5, 7, 8, 3], 'C': [564, 4545, 8989, 45, 23, 78]})
merged1 = gt.merge(ta, tb, 'A')

tc = gt.Table({'A': [1, 7], 'D': [np.datetime64('2017-02-15'), np.datetime64('2017-03-28')]})
merged2 = gt.merge(merged1, tc, 'A')

merged2.filter(merged2.B > 3)`
```
Okay, so, to my understanding, this should be okay as we are not doing anything too strange here. However, it doesn't work. Gtable (I think) complains about indexes dimension: 

> IndexError: index 10 is out of bounds for axis 1 with size 6

I'm guessing this has something to do with the handling of 0 indexes, but I'm not sure. I'm also almost positive that I've only encountered this issue when datetime columns were involved, even though the column that throws the exception is not datetime.

If you can give me some guidance about what is not working I can try to fix it, if you won't/can't.

Best regards!

**Comment by guillemborrell** [comment]
There is a bug in merge, since the index and the values of the column C are unbalanced.

```In [34]: ta = gt.Table({'A': [1,2,3,1,2,3,6], 'B': np.random.rand(7)})
In [35]: tb = gt.Table({'A': [1,2,5,7,8,3], 'C':np.random.rand(6)})
In [36]: tc = gt.Table({'A':[1,7], 'D': np.random.rand(2)})
In [37]: gt.merge(gt.merge(ta, tb, 'A'), tc, 'A').C.index
Out[37]: array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1], dtype=uint8)
In [38]: gt.merge(gt.merge(ta, tb, 'A'), tc, 'A').C.values
Out[38]:
array([ 0.82918058,  0.17884515,  0.044184  ,  0.06353509,  0.58242296,
        0.00735482])
In [41]: len(gt.merge(gt.merge(ta, tb, 'A'), tc, 'A').C.values)
Out[41]: 6
In [42]: gt.merge(gt.merge(ta, tb, 'A'), tc, 'A').C.index.sum()
Out[42]: 13
```
However, the first merge is successful

```
In [72]: [l for l in map(len, gt.merge(ta, tb, 'A').data)]
Out[72]: [7, 13, 6]

In [73]: gt.merge(ta, tb, 'A').index.sum(axis=1)
Out[73]: array([ 7, 13,  6], dtype=uint32)
```

@carlamj do you think you can handle it? I can't give any attention to this until friday.

**Comment by carlamj** [comment]
I'll try during the labor week and post any relevant updates on Friday @guillemborrell

**Comment by guillemborrell** [comment]
Please, confirm that a99e4d3090984141f6643c7215ec4f553cc20883 and version 0.7.4 fixes the issue. Close if that's the case.

**Comment by carlamj** [comment]
Well, that was fast. 

@guillemborrell thanks!
